version: '3.4'

services:
  runotp.webapp:
    container_name: runotp.webapp
    image: lebatuananh/runotp.webapp
    build:
      context: .
      dockerfile: scripts/Dockerfile
    ports:
      - "5201:80"

networks:
  my_network:
    external: true
