version: '3.4'

services:
  runotp.webapi:
    container_name: runotp.webapi
    image: lebatuananh/runotp.webapi
    build:
      context: .
      dockerfile: src/app/RunOtp.WebApi/Dockerfile
    env_file:
      - .env
    ports:
      - "5200:80"

networks:
  my_network:
    external: true        