// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace RunOtp.WebApp
{
    public partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var auditLog = AuditLogEntityType.Create(this);
            var identityRoleClaimGuid = IdentityRoleClaimGuidEntityType.Create(this);
            var identityUserClaimGuid = IdentityUserClaimGuidEntityType.Create(this);
            var identityUserLoginGuid = IdentityUserLoginGuidEntityType.Create(this);
            var identityUserRoleGuid = IdentityUserRoleGuidEntityType.Create(this);
            var identityUserTokenGuid = IdentityUserTokenGuidEntityType.Create(this);
            var appRole = AppRoleEntityType.Create(this);
            var appUser = AppUserEntityType.Create(this);
            var log = LogEntityType.Create(this);

            IdentityRoleClaimGuidEntityType.CreateForeignKey1(identityRoleClaimGuid, appRole);
            IdentityUserClaimGuidEntityType.CreateForeignKey1(identityUserClaimGuid, appUser);
            IdentityUserLoginGuidEntityType.CreateForeignKey1(identityUserLoginGuid, appUser);
            IdentityUserRoleGuidEntityType.CreateForeignKey1(identityUserRoleGuid, appRole);
            IdentityUserRoleGuidEntityType.CreateForeignKey2(identityUserRoleGuid, appUser);
            IdentityUserTokenGuidEntityType.CreateForeignKey1(identityUserTokenGuid, appUser);

            AuditLogEntityType.CreateAnnotations(auditLog);
            IdentityRoleClaimGuidEntityType.CreateAnnotations(identityRoleClaimGuid);
            IdentityUserClaimGuidEntityType.CreateAnnotations(identityUserClaimGuid);
            IdentityUserLoginGuidEntityType.CreateAnnotations(identityUserLoginGuid);
            IdentityUserRoleGuidEntityType.CreateAnnotations(identityUserRoleGuid);
            IdentityUserTokenGuidEntityType.CreateAnnotations(identityUserTokenGuid);
            AppRoleEntityType.CreateAnnotations(appRole);
            AppUserEntityType.CreateAnnotations(appUser);
            LogEntityType.CreateAnnotations(log);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.3");
            AddAnnotation("Relational:DefaultSchema", "data");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
